### ISSUE TITLE
Sample rate changes not handled properly

### ISSUE THREAD

**Issue by falkTX** [SpotlightKid/cookiecutter-dpf-audiotk#1]
I see that you're caching the sample rate value on init, via fSampleRate private variable.
This variable is never changed though.
Please override the sampleRateChanged callback to listen to those, and put the current activate() code in there.

**Comment by SpotlightKid** [comment]
Will do. Not sure from where I got this code. Is `sampleRateChanged` always called when the plugin is activated before `run` is called the first time?

**Comment by falkTX** [comment]
no, sampleRateChanged will not be called during 1st init (unless the host is weird...).
you can call that yourself though if you wish to save some code duplication.

**Comment by SpotlightKid** [comment]
Fixed in 0bb9d05.
